# Numpy

###  1. Introduction to NumPy
What NumPy is and why it’s important for numerical computations in Python.
Installation of NumPy (pip install numpy).
Understanding its role in data science, machine learning, and scientific computing.

* NumPy is a Python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier transform, and matrices.

* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

* NumPy stands for Numerical Python.

* It is use to solve the complex number.

### 2. Understanding the concept of ndarray (N-dimensional array).


* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

* Arrays are very frequently used in data science, where speed and resources are very important.

#### Creating arrays using np.array(), np.zeros(), np.ones(), np.arange(), and np.linspace().

In [1]:
import numpy as np 
arr = np.array([1 , 2 , 3 , 4 , 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
arr = np.array(500)
print(arr)

500


In [3]:
import numpy as np
arr = np.array([23,45,65,76,98])
print(arr)

[23 45 65 76 98]


In [6]:
import numpy as np
arr = np.array([[1,2,3,4,5],[7,8,9,10,11]])
print(arr)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [7]:
import numpy as np
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
arr = np.linspace(0,1, num=20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [14]:
import numpy as np 
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,3])

8


In [12]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[5:])

[6 7]


#### Arithmetic operations

* 1)Add

In [15]:
import numpy as np
a= np.array([45,78,56,90])
b= np.array([21,12,32,43])
add_ans = np.add(a,b)
print(add_ans)


[ 66  90  88 133]


* 2)Subtract

In [17]:
import numpy as np
a= np.array([45,78,56,90])
b= np.array([21,12,32,43])
sub_ans = np.subtract(a,b)
print(sub_ans)

[24 66 24 47]


* 3)Multiply

In [18]:
import numpy as np
a= np.array([45,78,56,90])
b= np.array([21,12,32,43])
mul_ans = np.multiply(a,b)
print(mul_ans)

[ 945  936 1792 3870]


* 4)Divide

In [19]:
import numpy as np
a= np.array([45,78,56,90])
b= np.array([21,12,32,43])
div_ans = np.divide(a,b)
print(div_ans)

[2.14285714 6.5        1.75       2.09302326]


### Broadcasting

In [21]:
import numpy as np
arr = np.array([1,2,3,4])
res = arr + 2
print(res)

[3 4 5 6]


In [23]:
import numpy as np
arr1 = np.array([12,43,54,67])
arr2 = np.array([56,89,65,31])
res = arr1 + arr2
print(res)

[ 68 132 119  98]


In [24]:
import numpy as np
arr = np.array([1,2,3,4,5])
a = np.shape(arr)
print(a)

(5,)


* Element-wise operations and functions

In [25]:
import numpy as np    
a = np.array([4, 5, 6])
arr = np.sqrt(a)  # square root
print(arr)

[2.         2.23606798 2.44948974]


In [26]:
import numpy as np    
a = np.array([7,8,9])
arr = np.sin(a)  # Trignometric Function Sine
print(arr)

[0.6569866  0.98935825 0.41211849]


In [27]:
import numpy as np    
a = np.array([12,13,14])
arr = np.exp(a)  # Calculates Exponential Values
print(arr)

[ 162754.791419    442413.39200892 1202604.28416478]


 # Array Shapes and Reshaping

* Checking array dimensions with .shape and .ndim.

In [28]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a = np.shape(arr)
print(a)

(2, 5)


In [31]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a = np.ndim(arr)
print(a)

2


* Changing array shape with .reshape(), .flatten(), .transpose().

In [38]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a= arr.flatten()
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [41]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr = arr.reshape(3,3)
print(newarr)
arr1 = newarr.transpose()
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


* Concatenating and splitting arrays using np.concatenate(), np.vstack(), np.hstack(), np.split().

In [43]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array ([5,6,7,8])
arr = np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6 7 8]


In [44]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array ([5,6,7,8])
arr = np.vstack((a,b))
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [45]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array ([5,6,7,8])
arr = np.hstack((a,b))
print(arr)

[1 2 3 4 5 6 7 8]


In [46]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6 , 7 , 8])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


#### Array Manipulation


* Indexing and slicing: understanding multi-dimensional arrays.

In [47]:
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
 
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [52]:
import numpy as np
arr1 =np.array([[1,4,5,6],[7,8,9,10],[21,23,43,54]])
print(arr1[2])# indexing
print(arr1[0:5])# slicing

[21 23 43 54]
[[ 1  4  5  6]
 [ 7  8  9 10]
 [21 23 43 54]]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print(mask) 
print(arr[mask])  # Output: [4 5 6]
arr[arr % 2 == 0] = 0
print(arr)  # Output: [1 0 3 0 5 0]

[False False False  True  True  True]
[4 5 6]
[1 0 3 0 5 0]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])


indices = [0, 2, 4]
print(arr[indices]) 
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rows = [0, 1, 2]
cols = [2, 0, 1]
print(arr_2d[rows, cols]) 

### 6. Mathematical Functions

* Universal functions (ufuncs) like np.add(), np.subtract(), np.multiply()

In [53]:
import numpy as np
a= np.array([45,78,56,90])
b= np.array([21,12,32,43])
add_ans = np.add(a,b)
print(add_ans)

[ 66  90  88 133]


In [54]:
import numpy as np
a= np.array([45,78,56,90])
b= np.array([21,12,32,43])
sub_ans = np.subtract(a,b)
print(sub_ans)

[24 66 24 47]


In [55]:
import numpy as np
a= np.array([45,78,56,90])
b= np.array([21,12,32,43])
mul_ans = np.multiply(a,b)
print(mul_ans)

[ 945  936 1792 3870]


In [56]:
import numpy as np
a= np.array([45,78,56,90])
b= np.array([21,12,32,43])
div_ans = np.divide(a,b)
print(div_ans)

[2.14285714 6.5        1.75       2.09302326]


* Statistical functions: np.mean(), np.median(), np.std(), np.var(), np.min(), np.max().

In [59]:
import numpy as np
a= np.array([1,2,3])
arr = np.mean(a)
print(arr)

2.0


In [60]:
import numpy as np
a= np.array([1,2,3,4,5])
arr = np.median(a)
print(arr)

3.0


In [61]:
import numpy as np
a= np.array([1,2,3,4,5])
arr = np.std(a)
print(arr)

1.4142135623730951


In [62]:
import numpy as np
a= np.array([1,2,3,4,5])
arr = np.var(a)
print(arr)

2.0


In [63]:
import numpy as np
a= np.array([1,2,3,4,5])
arr = np.max(a)
print(arr)

5


In [64]:
import numpy as np
a= np.array([1,2,3,4,5])
arr = np.min(a)
print(arr)

1


* Linear algebra functions: np.dot(), np.matmul(), np.linalg.inv(), np.linalg.eig().


In [2]:

import numpy as geek

product = geek.dot(5, 4)
print("Dot Product of scalar values : ", product)

vector_a = 2 + 3j
vector_b = 4 + 5j

product = geek.dot(vector_a, vector_b)
print("Dot Product : ", product)


Dot Product of scalar values :  20
Dot Product :  (-7+22j)


In [4]:
import numpy.matlib 
import numpy as np 

a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print (np.matmul(a,b))


[[4 1]
 [2 2]]


In [5]:

import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 

print("Rank of A:", np.linalg.matrix_rank(A))
 
print("\nTrace of A:", np.trace(A))
 
print("\nDeterminant of A:", np.linalg.det(A)) # np.linalg.det
 
print("\nInverse of A:\n", np.linalg.inv(A)) # np.linalg.inv
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [6]:
import numpy as np 


mat = np.mat("1 -2;1 3")  
print(mat) 
print("") 
evalue, evect = np.linalg.eig(mat)  
print(evalue) 
print("") 
print(evect) 

[[ 1 -2]
 [ 1  3]]

[2.+1.j 2.-1.j]

[[ 0.81649658+0.j          0.81649658-0.j        ]
 [-0.40824829-0.40824829j -0.40824829+0.40824829j]]
